#!/usr/bin/env bash
# This script checks the IP address of a given domain and its subdomains

# Check if the script is called with at least one argument
if [ $# -lt 1 ]; then
	echo "Usage: $0 domain [subdomain1 subdomain2 ...]"
	exit 1
fi

domain="$1"

# Define an array of default subdomains
subdomains=("www" "lb-01" "web-01" "web-02")

# If additional subdomains are provided, append them to the array
if [ $# -gt 1 ]; then
	subdomains+=("${@:2}")
fi

# Iterate over each subdomain in the array
for subdomain in "${subdomains[@]}"; do
	# Use dig command to get the IP address of the subdomain
	output=$(dig "$subdomain.$domain" +short)
	
	# Check if the output is not empty
	if [ -n "$output" ]; then
		echo "The subdomain $subdomain has IP address $output"
	else
		echo "The subdomain $subdomain does not exist"
	fi
done
