#!/usr/bin/env bash
# This script configures a brand new Ubuntu machine with Nginx

apt-get update
apt-get install -y nginx

sudo service nginx start

# Configure nginx to listen on port 80
sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Restart nginx
service nginx restart

# allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Create a temporary index.html file
echo "Hello World!" > /var/www/html/index.html

# Return the page containing "Hello World!" when querying Nginx at its root
sed -i 's/index index.html index.htm;/index index.html index.htm;\n\tlocation \/ {\n\t\treturn 200 "Hello World!";\n\t}/g' /etc/nginx/sites-available/default

# Configure Nginx to redirect /redirect_me to "https://www.youtube.com/watch?v=QH2-TGUlwu4" with a 301 Moved Permanently status
sudo sed -i 's/location \/ {/location \/redirect_me {\n\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n}\n\nlocation \/ {\n/g' /etc/nginx/sites-available/default

# Restart Nginx without using systemctl
sudo service nginx restart
