#!/usr/bin/env bash
# This script installs and configures Nginx on a brand new Ubuntu machine

# Install Nginx
apt-get update
apt-get install -y nginx

# Configure Nginx to listen on port 80
sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Create a custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configure Nginx to use the custom 404 page
sed -i '/error_page 404/c\        error_page 404 /404.html;' /etc/nginx/sites-available/default

# Configure Nginx to redirect /redirect_me to "https://www.youtube.com/watch?v=QH2-TGUlwu4"
echo 'location /redirect_me {
	return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
}' >> /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart
