#!/usr/bin/env bash
# fixes the issue of Nginx not listening on port 80
# rmove the default Nginx configuration file
sudo rm -f /etc/nginx/sites-enabled/default
#configure Nginx to listen on port 80 for all available IPv4 IPs
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
#restart Nginx
sudo service nginx restart
