#!/usr/bin/env bash
# a Bash script that displays numbers from 1 to 20
HOURS=0
while [ $HOURS -lt 13 ]
do
    echo "Hour: $HOURS"
    MINUTES=1
    while [ $MINUTES -lt 60 ]
    do
        echo $MINUTES
	(( MINUTES+=1 ))
    done
    (( HOURS+=1 ))
done