#!/usr/bin/env bash
# Write a Bash script that displays:

# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed (refer to the example)
# You must use the for loop (while and until are forbidden)
# Do not display hidden files

for file in *; do
    echo "$file" | cut -d '-' -f 2
done