#!/usr/bin/env bash
# This script configures nginx to run as the nginx user, listen on all active IPs on port 8080, and does not use apt-get remove
sudo apt-get install -y nginx
sudo sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sudo sed -i 's/listen 80 default_server;/listen 8080 default_server;/g' /etc/nginx/sites-available/default
sudo service nginx restart
